# Generated by Django 3.2.7 on 2021-09-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('earnings', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=50)),
                ('goal_total', models.FloatField(default=0)),
                ('balance_saved', models.FloatField(default=0)),
                ('acomplish_date', models.DateTimeField(verbose_name='completion date')),
                ('payment_deductions', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetProfiler.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=50)),
                ('cost', models.FloatField(default=0)),
                ('occurance_rate', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-weekly', 'Bi-weekly')], default=('monthly', 'Monthly'), max_length=9)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetProfiler.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_name', models.CharField(max_length=50)),
                ('balance_remaining', models.FloatField(default=0)),
                ('interest', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetProfiler.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('saving', 'Savings'), ('debit', 'Debit')], default=('debit', 'Debit'), max_length=8)),
                ('account_balance', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetProfiler.profile')),
            ],
        ),
    ]
